#!/bin/bash

opts="${BENCH_OPTS}"
echo ""
echo "Extra bench opts: ${opts}"
echo ""

cyan=$(tput setaf 6)
underline=$(tput smul)
normal=$(tput sgr0)
function title() {
    echo -e "${cyan}${underline}" "$@" "${normal}"
}

function bench() {
    go test -run=NONE -benchmem -benchtime=10s -bench=. ${opts} ./... | tee "$@" | prettybench
}

oldf=bench1.out
newf=bench2.out
rm -f "${oldf}" "${newf}"

set -e

title "Benchmarking without current changes: ${oldf}"
git stash
bench ${oldf}

title "Benchmarking WITH changes: ${newf}"
git stash pop
bench ${newf}

title "Comparing benchmarks ${oldf} -- ${newf}"
benchstat ${oldf} ${newf}
