#!/bin/bash

set -e

cyan=$(tput setaf 6)
underline=$(tput smul)
normal=$(tput sgr0)
function title() {
    echo -e "${cyan}${underline}" "$@" "${normal}"
}

title "go vet"
go vet $(go list ./...) 2>&1 | ./script/color.py

title "golangci-lint"
golangci-lint run --color=never 2>&1 | ./script/color.py
