#!/usr/bin/env python3

import re
import subprocess


def main():
    with open('Gopkg.toml') as fh:
        lines = [i.strip() for i in fh]

    name_r = re.compile(r'name = \"([^\"]+)\"')

    for line in lines:
        if not line or line[0] == '#':
            continue

        m = name_r.match(line)
        if not m:
            continue

        pkg = m.groups(0)[0]
        print('\033[91m{}\033[0m'.format(pkg))
        subprocess.run(['go', 'get', '-v', '-u', pkg], check=True)


if __name__ == '__main__':
    main()
