#!/usr/bin/env python3

import re
import subprocess


def all_deps():
    # Unconditionally yield prettybench (see `./bench`)
    yield 'github.com/cespare/prettybench'
    # Unconditionally get all of gonum before we analyze the Gopkg file
    yield 'gonum.org/v1/gonum/...'

    with open('Gopkg.toml') as fh:
        lines = [i.strip() for i in fh]

    name_r = re.compile(r'name = \"([^\"]+)\"')

    for line in lines:
        if not line or line[0] == '#':
            continue

        m = name_r.match(line)
        if not m:
            continue

        yield m.groups(0)[0]


def main():
    for pkg in all_deps():
        print('\033[91m{}\033[0m'.format(pkg))
        subprocess.run(['go', 'get', '-v', '-t', '-u', pkg], check=True)


if __name__ == '__main__':
    main()
