#!/bin/bash

cyan=$(tput setaf 6)
underline=$(tput smul)
normal=$(tput sgr0)
function title() {
    echo -e "${cyan}${underline}" "$@" "${normal}"
}

title "Installing Go perf/prod/benchmark tools"
go install golang.org/x/perf/cmd/...@latest

#title "Installing golangci-lint"
#go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

title "Performing go mod tidy"
go mod tidy